In [11]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split


In [12]:
data=pd.read_csv('age_salary (1).csv')
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [13]:
x=data.iloc[:,1:4 ]
x


Gender  Age  EstimatedSalary
0      Male   19            19000
1      Male   35            20000
2    Female   26            43000
3    Female   27            57000
4      Male   19            76000
..      ...  ...              ...
395  Female   46            41000
396    Male   51            23000
397  Female   50            20000
398    Male   36            33000
399  Female   49            36000

[400 rows x 3 columns]

In [14]:
gender_mapping ={'Male':1,'Female':0}
x['Gender']=x['Gender'].map(gender_mapping)
x

Gender  Age  EstimatedSalary
0         1   19            19000
1         1   35            20000
2         0   26            43000
3         0   27            57000
4         1   19            76000
..      ...  ...              ...
395       0   46            41000
396       1   51            23000
397       0   50            20000
398       1   36            33000
399       0   49            36000

[400 rows x 3 columns]

In [15]:
x=x.values
x

array([[    1,    19, 19000],
       [    1,    35, 20000],
       [    0,    26, 43000],
       ...,
       [    0,    50, 20000],
       [    1,    36, 33000],
       [    0,    49, 36000]])

In [16]:
y=data['Purchased'].values
y.shape

(400,)

In [17]:
xtrain,xtest,ytrain,ytest=train_test_split (x,y,test_size=0.2,random_state=0)


In [18]:
xtrain.shape


(320, 3)

In [19]:
ytrain.shape

(320,)

In [21]:


model=SVC(kernel='rbf',random_state=1)
model1=LogisticRegression(random_state=1, solver='liblinear',multi_class='auto')
model2=KNeighborsClassifier(n_neighbors=11)

In [22]:
model.fit(xtrain,ytrain)

SVC(random_state=1)

In [23]:
model1.fit(xtrain,ytrain)

LogisticRegression(random_state=1, solver='liblinear')

In [24]:
model2.fit(xtrain,ytrain)
KNeighborsClassifier(n_neighbors=11)

KNeighborsClassifier(n_neighbors=11)

In [26]:
ypredict=model.predict(xtest)
ypredict

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [27]:
ypredict1=model1.predict(xtest)
ypredict1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1])

In [28]:
ypredit2=model2.predict(xtest)
ypredict

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [29]:
ytest

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1])

In [30]:
model.score(xtest,ytest)

0.825

In [31]:
model1.score(xtest,ytest)

0.7875

In [ ]:
model2.score(xtest,ytest)

0.8875

In [32]:
from sklearn.metrics import mean_squared_error
mean_squared_error(ytest,ypredict)

0.175

In [33]:
mean_squared_error(ytest,ypredict1)

0.2125

In [34]:
mean_squared_error(ytest,ypredit2) 

0.1125

In [43]:
from numpy.matrixlib import defmatrix
import numpy as np
import pandas as pd
from numpy.ma.core import array
gender=int(input('please insert 1 for mail or 0 for femail'))
age=int(input('please insert your age'))
salary=int(input('please insert your salary '))

data = {
  "gender": [gender],
  "age": [age],
  "salary":[salary]
}

df = pd.DataFrame(data)
x=df.values
ypnemoneh=model.predict(x)
ypnemoneh
ypnemoneh2=model2.predict(x)
ypnemoneh2
ypnemoneh1=model1.predict(x)
ypnemoneh1

please insert 1 for mail or 0 for femail1
please insert your age25
please insert your salary 30000


array([0])